// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCV.Contexts;

namespace WebApiCV.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210410005246_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiCV.Entity.CarreraProfesional", b =>
                {
                    b.Property<int>("nCarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cCarNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nCarId");

                    b.ToTable("CarreraProfesional");
                });

            modelBuilder.Entity("WebApiCV.Entity.Curriculo", b =>
                {
                    b.Property<long>("nCurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cCurAcerca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurApellidMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurApellidPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurDni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurMovil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurNombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cUbiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dCurFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nCarId")
                        .HasColumnType("int");

                    b.Property<bool>("nEstado")
                        .HasColumnType("bit");

                    b.Property<int>("nGacId")
                        .HasColumnType("int");

                    b.HasKey("nCurId");

                    b.HasIndex("cUbiId");

                    b.HasIndex("nCarId");

                    b.HasIndex("nGacId");

                    b.ToTable("Curriculo");
                });

            modelBuilder.Entity("WebApiCV.Entity.Formacion", b =>
                {
                    b.Property<long>("nForId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cForDiplomaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nForAnioFin")
                        .HasColumnType("int");

                    b.Property<int>("nForAnioInicio")
                        .HasColumnType("int");

                    b.Property<int>("nForCarreraProfesionalId")
                        .HasColumnType("int");

                    b.Property<long>("nForCurriculoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("nForEstado")
                        .HasColumnType("bit");

                    b.Property<int>("nForGradoAcademicoId")
                        .HasColumnType("int");

                    b.Property<long>("nForInstitucionId")
                        .HasColumnType("bigint");

                    b.HasKey("nForId");

                    b.HasIndex("nForCarreraProfesionalId");

                    b.HasIndex("nForCurriculoId");

                    b.HasIndex("nForGradoAcademicoId");

                    b.HasIndex("nForInstitucionId");

                    b.ToTable("Formacion");
                });

            modelBuilder.Entity("WebApiCV.Entity.GradoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cGacNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GradoAcademico");
                });

            modelBuilder.Entity("WebApiCV.Entity.Institucion", b =>
                {
                    b.Property<long>("nInsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cInsAcronimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cInsFundacion")
                        .HasColumnType("int");

                    b.Property<string>("cInsNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cInsSede")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nInsId");

                    b.ToTable("Institucion");
                });

            modelBuilder.Entity("WebApiCV.Entity.Ubigeo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cUbiDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cUbiDistrito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cUbiProvincia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ubigeo");
                });

            modelBuilder.Entity("WebApiCV.ModelsProcedure.RecordPostulantes", b =>
                {
                    b.Property<long>("nCurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cCurApellidMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurApellidPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurDni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cCurNombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dCurFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("nCurId");

                    b.ToTable("RecordPostulantes");
                });

            modelBuilder.Entity("WebApiCV.Entity.Curriculo", b =>
                {
                    b.HasOne("WebApiCV.Entity.Ubigeo", "Ubigeo")
                        .WithMany()
                        .HasForeignKey("cUbiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCV.Entity.CarreraProfesional", "CarreraProfesional")
                        .WithMany()
                        .HasForeignKey("nCarId");

                    b.HasOne("WebApiCV.Entity.GradoAcademico", "GradoAcademico")
                        .WithMany()
                        .HasForeignKey("nGacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarreraProfesional");

                    b.Navigation("GradoAcademico");

                    b.Navigation("Ubigeo");
                });

            modelBuilder.Entity("WebApiCV.Entity.Formacion", b =>
                {
                    b.HasOne("WebApiCV.Entity.CarreraProfesional", "CarreraProfesional")
                        .WithMany()
                        .HasForeignKey("nForCarreraProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCV.Entity.Curriculo", "Curriculo")
                        .WithMany("lFormacion")
                        .HasForeignKey("nForCurriculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCV.Entity.GradoAcademico", "GradoAcademico")
                        .WithMany()
                        .HasForeignKey("nForGradoAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCV.Entity.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("nForInstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarreraProfesional");

                    b.Navigation("Curriculo");

                    b.Navigation("GradoAcademico");

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("WebApiCV.Entity.Curriculo", b =>
                {
                    b.Navigation("lFormacion");
                });
#pragma warning restore 612, 618
        }
    }
}
